-- Milestone 4: Create the private storage bucket for client file uploads.
-- Run this once in Supabase's SQL Editor.
--
-- Note: we're deliberately NOT adding Storage RLS policies here. Every
-- upload/read in our app goes through a signed URL generated by our
-- service-role Server Actions (see lib/actions/upload-actions.ts) — the
-- signed token itself is the authorization for that specific file, so
-- bucket-level RLS policies would be redundant for our current access
-- pattern. If we ever add direct anon-key access to files later, revisit this.

insert into storage.buckets (id, name, public)
values ('onboarding-assets', 'onboarding-assets', false)
on conflict (id) do nothing;
